import { Course, Widget } from "@/models";
import { Meta } from "@/models/meta";

export default async function getUserOrganization(): Promise<any> {
//   await new Promise((resolve) => setTimeout(resolve, 500));
  const user ={
    "id": "NitJpeJuvAx3ZcawJ",
    "name": "Vũ Hồng Phong",
    "username": "+84112233444",
    "email": "demotanca+009@gmail.com",
    "is_tanca_email": null,
    "phone": "+84112233444",
    "phone_code": "84",
    "is_tanca_phone": null,
    "address": "217/4 nơ trang long quận bình thạnh",
    "birthday": "2018-02-16",
    "sex": 1,
    "identify_card": null,
    "status": "active",
    "is_root": 1,
    "birthplace": null,
    "sub_department": null,
    "sub_team": null,
    "nationality": null,
    "seniority_date": null,
    "name_no_sign_shopee": null,
    "direct_manager_id": "",
    "crm_role": "",
    "crm_extra_roles": [],
    "alias": "vu-hong-phong",
    "is_identify": 1,
    "is_passport": 1,
    "other_info": {
        "is_insurrance": 0,
        "ethnic": "",
        "religion": "",
        "is_married": 0,
        "emergency_contact": null,
        "emergency_relate": null,
        "skype": null,
        "facebook": null,
        "emergency_tel": null,
        "emergency_phone": null,
        "emergency_address": null,
        "height": null,
        "weight": null,
        "blood_id": "",
        "congenital": null,
        "health_id": "",
        "health_last_date": null,
        "educational_level_id": "",
        "note": null
    },
    "permanent": {
        "domicile": "hue"
    },
    "organization_id": "NitJpeJuvAx3ZcawJ",
    "user_id": "NitJpeJuvAx3ZcawJ",
    "package": [],
    "shop_id": "5c20a19c0b08880f594fc468",
    "region_id": "62d131512e4ab3464c4d4c6d",
    "branch_id": "66ba2caea46a76a5d506cea9",
    "position_id": "",
    "department_id": "",
    "group_id": "5aae8b88dd8e8437e90e24bd",
    "salary": 10000000,
    "tax": null,
    "union": null,
    "client_role": "MANAGER",
    "identification": "12345555555555555666666",
    "payroll_config_element_id": "5afe4d1ce42f7212ff7a10a6",
    "payroll_config_id": null,
    "payroll_config_date": null,
    "labour_end_date": "2007-09-07 00:00:00",
    "working_date": "2025-02-13 00:00:00",
    "is_multi_mobile": 0,
    "is_in_out_without_wifi": 3,
    "is_no_need_timekeeping": 0,
    "is_auto_timekeeping": 0,
    "is_help_check_shift": 1,
    "is_clock_in_using_image": 0,
    "is_clock_out_using_image": 0,
    "is_location_tracking": 1,
    "is_enable_auto_login": 1,
    "is_inactive": 0,
    "is_allowing_early_check_in_out": 0,
    "is_allowing_lately_check_in_out": 0,
    "is_help_check_shift_using_image": 1,
    "is_auto_checkout": 0,
    "setting": {
        "share_location": 1,
        "clock_in_notification": 1,
        "late_clock_in_notification": 1,
        "over_clock_out_notification": 1,
        "clock_out_notification": 1
    },
    "updated_at": "2025-03-06 10:50:43",
    "is_head_of_department": 0,
    "is_quit": 0,
    "crm_noti_count": 0,
    "signature_image": "https://upload.tanca.io/api/upload/file-info/6180fc07a939ec3bd566add2",
    "sort_index": 117,
    "last_activity": "2025-03-06 10:50:43",
    "payroll_config_element_obj": {
        "id": "5afe4d1ce42f7212ff7a10a6",
        "name": "Chi trả theo tháng",
        "value": "by_month",
        "type": "payroll_config"
    },
    "checkin_late": 0,
    "checkout_early": 0,
    "total_minutes_check_late_early": 0,
    "total_minutes_check_late_early_flag": 0,
    "checkin_late_ranges": [],
    "checkout_early_ranges": [],
    "total_minutes_check_late_early_ranges": [],
    "shop_username": "tancaxaydung",
    "position": "",
    "department": "",
    "shop": "Công ty Globall",
    "region": "HCM",
    "branch": "CN Quận 6 HCM",
    "payroll_config": "Lương full time",
    "group": "Quản lý",
    "position_obj": null,
    "department_obj": null,
    "shop_obj": {
        "id": "5c20a19c0b08880f594fc468",
        "name": "Công ty Globall"
    },
    "region_obj": {
        "id": "62d131512e4ab3464c4d4c6d",
        "name": "HCM"
    },
    "branch_obj": {
        "id": "66ba2caea46a76a5d506cea9",
        "name": "CN Quận 6 HCM"
    },
    "payroll_config_obj": {
        "id": "64255353be6b0c52ec09aa2d",
        "name": "Lương full time"
    },
    "group_obj": {
        "id": "5aae8b88dd8e8437e90e24bd",
        "name": "Quản lý",
        "client_role": "MANAGER"
    },
    "user": {
        "active": true,
        "avatarOrigin": "upload",
        "birthday": "2018-02-16 00:00:00",
        "brandRepresent": null,
        "company": [],
        "email": "demotanca+009@gmail.com",
        "job": null,
        "language": "vi",
        "name": "Vũ Hồng Phong",
        "sex": 1,
        "status": "offline",
        "statusConnection": "offline",
        "statusDefault": "online",
        "username": "+84112233444",
        "utcOffset": 7,
        "_id": "NitJpeJuvAx3ZcawJ",
        "_version": 2,
        "apiToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vYXBpLnRhbmNhLmlvL2FwaS92NC9hdXRoL25ldy1sb2dpbiIsImlhdCI6MTY1OTM0NjcxNywibmJmIjoxNjU5MzQ2NzE3LCJqdGkiOiJ0cWJuTkVSRXlwRXZmU3NoIiwic3ViIjoiTml0SnBlSnV2QXgzWmNhd0oiLCJwcnYiOiIxYzU1MjBmNzBiYWE2NTVkZGM1NzQ2YTY3NjRmMzcyYTFiNjU1YWE2Iiwic2hvcF9pZCI6IjVjMjBhMTljMGIwODg4MGY1OTRmYzQ2OCIsInNob3BfdXNlcm5hbWUiOiJ0YW5jYWR1bGljaCIsInNob3BfcHJlZml4IjoidCJ9.aaiJdZuMttCLJOjp5uF8bymif8LIAA9jboQev2aUaX0"
    },
    "view_allowance_info": true,
    "disable_integration_menu": false,
    "can_update_permission": true,
    "can_update_timetracking_config": true,
    "export_file_permission": {
        "employee": 1,
        "insurance": 1,
        "contract": 1,
        "asset": 1,
        "timesheet": 1,
        "time_tracking": 1,
        "edit_time_tracking": 1,
        "request": 1,
        "payroll": 1,
        "kpi": 1,
        "task": 1,
        "my_report": 1,
        "request_approval": 1,
        "gps": 1,
        "wifi": 1,
        "qr": 1,
        "wanip": 1,
        "project": 1,
        "shift_list": 1,
        "who_is_working": 1,
        "meal": 1,
        "employee_dayleft": 1,
        "promotion_history": 1,
        "timesheet_task": 1
    },
    "lock_timesheet_permission": 1,
    "lock_timesheet_status": 1,
    "assign_import_task_timesheet_setting": true,
    "crud_task_timesheet_setting": true,
    "view_promotion_history": true,
    "can_use_publish_shifts": true,
    "shop_amount": 220
}
 return user
}
