export default function getToken(): string {
  // TODO: Replace with proper token management
  const token =
    'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vYXBpLnRhbmNhLmlvL2FwaS92NC9hdXRoL3NpZ25pbi12MiIsImlhdCI6MTc0MTIzNDY3NiwibmJmIjoxNzQxMjM0Njc2LCJqdGkiOiJvNk01YVhEV0h1a0dDUFRKIiwic3ViIjoiTml0SnBlSnV2QXgzWmNhd0oiLCJwcnYiOiIxYzU1MjBmNzBiYWE2NTVkZGM1NzQ2YTY3NjRmMzcyYTFiNjU1YWE2Iiwic2hvcF9pZCI6IjVjMjBhMTljMGIwODg4MGY1OTRmYzQ2OCIsInNob3BfdXNlcm5hbWUiOiJ0YW5jYXhheWR1bmciLCJzaG9wX3ByZWZpeCI6InQiLCJ0eXBlIjoiYXBpIn0.2RPOSAcs_yiHbtrBgUHlpIdxa4gI8qr8smK1ZDCJ_0U';
  return token;
}
